/*
 * D I S C L A I M E R          
 * 
 * WARNING: ANY USE BY YOU OF THE SAMPLE CODE PROVIDED IS AT YOUR OWN RISK.
 * 
 * Authorize.Net provides this code "as is" without warranty of any kind, either
 * express or implied, including but not limited to the implied warranties of 
 * merchantability and/or fitness for a particular purpose.   
 * Authorize.Net owns and retains all right, title and interest in and to the 
 * Automated Recurring Billing intellectual property.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace JordanRift.Grassroots.Framework.Services
{
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot("ErrorResponse", Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ANetApiResponse
    {

        /// <remarks/>
        public string refId;

        /// <remarks/>
        public messagesType messages;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class messagesType
    {

        /// <remarks/>
        public messageTypeEnum resultCode;

        /// <remarks/>
        [XmlElement("message")]
        public messagesTypeMessage[] message;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum messageTypeEnum
    {

        /// <remarks/>
        Ok,

        /// <remarks/>
        Error,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class messagesTypeMessage
    {

        /// <remarks/>
        public string code;

        /// <remarks/>
        public string text;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransVoidType
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public string customerShippingAddressId;

        /// <remarks/>
        public string transId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class lineItemType
    {

        /// <remarks/>
        public string itemId;

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string description;

        /// <remarks/>
        public decimal quantity;

        /// <remarks/>
        public decimal unitPrice;

        /// <remarks/>
        public bool taxable;

        /// <remarks/>
        [XmlIgnore]
        public bool taxableSpecified;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class extendedAmountType
    {

        /// <remarks/>
        public decimal amount;

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string description;
    }

    /// <remarks/>
    [XmlInclude(typeof(profileTransRefundType))]
    [XmlInclude(typeof(profileTransPriorAuthCaptureType))]
    [XmlInclude(typeof(profileTransOrderType))]
    [XmlInclude(typeof(profileTransCaptureOnlyType))]
    [XmlInclude(typeof(profileTransAuthOnlyType))]
    [XmlInclude(typeof(profileTransAuthCaptureType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransAmountType
    {

        /// <remarks/>
        public decimal amount;

        /// <remarks/>
        public extendedAmountType tax;

        /// <remarks/>
        public extendedAmountType shipping;

        /// <remarks/>
        public extendedAmountType duty;

        /// <remarks/>
        [XmlElement("lineItems")]
        public lineItemType[] lineItems;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransRefundType : profileTransAmountType
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public string customerShippingAddressId;

        /// <remarks/>
        public string creditCardNumberMasked;

        /// <remarks/>
        public string bankRoutingNumberMasked;

        /// <remarks/>
        public string bankAccountNumberMasked;

        /// <remarks/>
        public orderExType order;

        /// <remarks/>
        public string transId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class orderExType : orderType
    {

        /// <remarks/>
        public string purchaseOrderNumber;
    }

    /// <remarks/>
    [XmlInclude(typeof(orderExType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class orderType
    {

        /// <remarks/>
        public string invoiceNumber;

        /// <remarks/>
        public string description;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransPriorAuthCaptureType : profileTransAmountType
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public string customerShippingAddressId;

        /// <remarks/>
        public string transId;
    }

    /// <remarks/>
    [XmlInclude(typeof(profileTransCaptureOnlyType))]
    [XmlInclude(typeof(profileTransAuthOnlyType))]
    [XmlInclude(typeof(profileTransAuthCaptureType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransOrderType : profileTransAmountType
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public string customerShippingAddressId;

        /// <remarks/>
        public orderExType order;

        /// <remarks/>
        public bool taxExempt;

        /// <remarks/>
        [XmlIgnore]
        public bool taxExemptSpecified;

        /// <remarks/>
        public bool recurringBilling;

        /// <remarks/>
        [XmlIgnore]
        public bool recurringBillingSpecified;

        /// <remarks/>
        public string cardCode;

        /// <remarks/>
        public string splitTenderId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransCaptureOnlyType : profileTransOrderType
    {

        /// <remarks/>
        public string approvalCode;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransAuthOnlyType : profileTransOrderType
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransAuthCaptureType : profileTransOrderType
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class profileTransactionType
    {

        /// <remarks/>
        [XmlElement("profileTransAuthCapture", typeof(profileTransAuthCaptureType))]
        [XmlElement("profileTransAuthOnly", typeof(profileTransAuthOnlyType))]
        [XmlElement("profileTransCaptureOnly", typeof(profileTransCaptureOnlyType))]
        [XmlElement("profileTransPriorAuthCapture", typeof(profileTransPriorAuthCaptureType))]
        [XmlElement("profileTransRefund", typeof(profileTransRefundType))]
        [XmlElement("profileTransVoid", typeof(profileTransVoidType))]
        public object Item;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class driversLicenseMaskedType
    {

        /// <remarks/>
        public string number;

        /// <remarks/>
        public string state;

        /// <remarks/>
        public string dateOfBirth;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class bankAccountMaskedType
    {

        /// <remarks/>
        public bankAccountTypeEnum accountType;

        /// <remarks/>
        [XmlIgnore]
        public bool accountTypeSpecified;

        /// <remarks/>
        public string routingNumber;

        /// <remarks/>
        public string accountNumber;

        /// <remarks/>
        public string nameOnAccount;

        /// <remarks/>
        public echeckTypeEnum echeckType;

        /// <remarks/>
        [XmlIgnore]
        public bool echeckTypeSpecified;

        /// <remarks/>
        public string bankName;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum bankAccountTypeEnum
    {

        /// <remarks/>
        checking,

        /// <remarks/>
        savings,

        /// <remarks/>
        businessChecking,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum echeckTypeEnum
    {

        /// <remarks/>
        PPD,

        /// <remarks/>
        WEB,

        /// <remarks/>
        CCD,

        /// <remarks/>
        TEL,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class creditCardMaskedType
    {

        /// <remarks/>
        public string cardNumber;

        /// <remarks/>
        public string expirationDate;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class paymentMaskedType
    {

        /// <remarks/>
        [XmlElement("bankAccount", typeof(bankAccountMaskedType))]
        [XmlElement("creditCard", typeof(creditCardMaskedType))]
        public object Item;
    }

    /// <remarks/>
    [XmlInclude(typeof(customerPaymentProfileMaskedType))]
    [XmlInclude(typeof(customerPaymentProfileType))]
    [XmlInclude(typeof(customerPaymentProfileExType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerPaymentProfileBaseType
    {

        /// <remarks/>
        public customerTypeEnum customerType;

        /// <remarks/>
        [XmlIgnore]
        public bool customerTypeSpecified;

        /// <remarks/>
        public customerAddressType billTo;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum customerTypeEnum
    {

        /// <remarks/>
        individual,

        /// <remarks/>
        business,
    }

    /// <remarks/>
    [XmlInclude(typeof(customerAddressExType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerAddressType : nameAndAddressType
    {

        /// <remarks/>
        public string phoneNumber;

        /// <remarks/>
        public string faxNumber;
    }

    /// <remarks/>
    [XmlInclude(typeof(customerAddressType))]
    [XmlInclude(typeof(customerAddressExType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class nameAndAddressType
    {

        /// <remarks/>
        public string firstName;

        /// <remarks/>
        public string lastName;

        /// <remarks/>
        public string company;

        /// <remarks/>
        public string address;

        /// <remarks/>
        public string city;

        /// <remarks/>
        public string state;

        /// <remarks/>
        public string zip;

        /// <remarks/>
        public string country;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerAddressExType : customerAddressType
    {

        /// <remarks/>
        public string customerAddressId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerPaymentProfileMaskedType : customerPaymentProfileBaseType
    {

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public paymentMaskedType payment;

        /// <remarks/>
        public driversLicenseMaskedType driversLicense;

        /// <remarks/>
        public string taxId;
    }

    /// <remarks/>
    [XmlInclude(typeof(customerPaymentProfileExType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerPaymentProfileType : customerPaymentProfileBaseType
    {

        /// <remarks/>
        public paymentType payment;

        /// <remarks/>
        public driversLicenseType driversLicense;

        /// <remarks/>
        public string taxId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class paymentType
    {

        /// <remarks/>
        [XmlElement("bankAccount", typeof(bankAccountType))]
        [XmlElement("creditCard", typeof(creditCardType))]
        public object Item;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class bankAccountType
    {

        /// <remarks/>
        public bankAccountTypeEnum accountType;

        /// <remarks/>
        [XmlIgnore]
        public bool accountTypeSpecified;

        /// <remarks/>
        public string routingNumber;

        /// <remarks/>
        public string accountNumber;

        /// <remarks/>
        public string nameOnAccount;

        /// <remarks/>
        public echeckTypeEnum echeckType;

        /// <remarks/>
        [XmlIgnore]
        public bool echeckTypeSpecified;

        /// <remarks/>
        public string bankName;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class creditCardType : creditCardSimpleType
    {

        /// <remarks/>
        public string cardCode;
    }

    /// <remarks/>
    [XmlInclude(typeof(creditCardType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class creditCardSimpleType
    {

        /// <remarks/>
        public string cardNumber;

        /// <remarks/>
        public string expirationDate;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class driversLicenseType
    {

        /// <remarks/>
        public string number;

        /// <remarks/>
        public string state;

        /// <remarks/>
        public string dateOfBirth;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerPaymentProfileExType : customerPaymentProfileType
    {

        /// <remarks/>
        public string customerPaymentProfileId;
    }

    /// <remarks/>
    [XmlInclude(typeof(customerProfileExType))]
    [XmlInclude(typeof(customerProfileMaskedType))]
    [XmlInclude(typeof(customerProfileType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerProfileBaseType
    {

        /// <remarks/>
        public string merchantCustomerId;

        /// <remarks/>
        public string description;

        /// <remarks/>
        public string email;
    }

    /// <remarks/>
    [XmlInclude(typeof(customerProfileMaskedType))]
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerProfileExType : customerProfileBaseType
    {

        /// <remarks/>
        public string customerProfileId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerProfileMaskedType : customerProfileExType
    {

        /// <remarks/>
        [XmlElement("paymentProfiles")]
        public customerPaymentProfileMaskedType[] paymentProfiles;

        /// <remarks/>
        [XmlElement("shipToList")]
        public customerAddressExType[] shipToList;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerProfileType : customerProfileBaseType
    {

        /// <remarks/>
        [XmlElement("paymentProfiles")]
        public customerPaymentProfileType[] paymentProfiles;

        /// <remarks/>
        [XmlElement("shipToList")]
        public customerAddressType[] shipToList;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class customerType
    {

        /// <remarks/>
        public customerTypeEnum type;

        /// <remarks/>
        [XmlIgnore]
        public bool typeSpecified;

        /// <remarks/>
        public string id;

        /// <remarks/>
        public string email;

        /// <remarks/>
        public string phoneNumber;

        /// <remarks/>
        public string faxNumber;

        /// <remarks/>
        public driversLicenseType driversLicense;

        /// <remarks/>
        public string taxId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class paymentScheduleType
    {

        /// <remarks/>
        public paymentScheduleTypeInterval interval;

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime startDate;

        /// <remarks/>
        [XmlIgnore]
        public bool startDateSpecified;

        /// <remarks/>
        public short totalOccurrences;

        /// <remarks/>
        [XmlIgnore]
        public bool totalOccurrencesSpecified;

        /// <remarks/>
        public short trialOccurrences;

        /// <remarks/>
        [XmlIgnore]
        public bool trialOccurrencesSpecified;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class paymentScheduleTypeInterval
    {

        /// <remarks/>
        public short length;

        /// <remarks/>
        public ARBSubscriptionUnitEnum unit;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum ARBSubscriptionUnitEnum
    {

        /// <remarks/>
        days,

        /// <remarks/>
        months,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class ARBSubscriptionType
    {

        /// <remarks/>
        public string name;

        /// <remarks/>
        public paymentScheduleType paymentSchedule;

        /// <remarks/>
        public decimal amount;

        /// <remarks/>
        [XmlIgnore]
        public bool amountSpecified;

        /// <remarks/>
        public decimal trialAmount;

        /// <remarks/>
        [XmlIgnore]
        public bool trialAmountSpecified;

        /// <remarks/>
        public paymentType payment;

        /// <remarks/>
        public orderType order;

        /// <remarks/>
        public customerType customer;

        /// <remarks/>
        public nameAndAddressType billTo;

        /// <remarks/>
        public nameAndAddressType shipTo;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class merchantAuthenticationType
    {

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string transactionKey;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public class ANetApiRequest
    {

        /// <remarks/>
        public merchantAuthenticationType merchantAuthentication;

        /// <remarks/>
        public string refId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class isAliveRequest
    {

        /// <remarks/>
        public string refId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class isAliveResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class authenticateTestRequest : ANetApiRequest
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class authenticateTestResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBCreateSubscriptionRequest : ANetApiRequest
    {

        /// <remarks/>
        public ARBSubscriptionType subscription;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBCreateSubscriptionResponse : ANetApiResponse
    {

        /// <remarks/>
        public string subscriptionId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBUpdateSubscriptionRequest : ANetApiRequest
    {

        /// <remarks/>
        public string subscriptionId;

        /// <remarks/>
        public ARBSubscriptionType subscription;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBUpdateSubscriptionResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBCancelSubscriptionRequest : ANetApiRequest
    {

        /// <remarks/>
        public string subscriptionId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBCancelSubscriptionResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBGetSubscriptionStatusRequest : ANetApiRequest
    {

        /// <remarks/>
        public string subscriptionId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class ARBGetSubscriptionStatusResponse : ANetApiResponse
    {

        /// <remarks/>
        public ARBSubscriptionStatusEnum Status;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum ARBSubscriptionStatusEnum
    {

        /// <remarks/>
        active,

        /// <remarks/>
        expired,

        /// <remarks/>
        suspended,

        /// <remarks/>
        canceled,

        /// <remarks/>
        terminated,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public customerProfileType profile;

        /// <remarks/>
        public validationModeEnum validationMode;

        /// <remarks/>
        [XmlIgnore]
        public bool validationModeSpecified;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum validationModeEnum
    {

        /// <remarks/>
        none,

        /// <remarks/>
        testMode,

        /// <remarks/>
        liveMode,

        /// <remarks/>
        oldLiveMode,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerProfileResponse : ANetApiResponse
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        [XmlArrayItem("numericString", IsNullable = false)]
        public string[] customerPaymentProfileIdList;

        /// <remarks/>
        [XmlArrayItem("numericString", IsNullable = false)]
        public string[] customerShippingAddressIdList;

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public string[] validationDirectResponseList;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerPaymentProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public customerPaymentProfileType paymentProfile;

        /// <remarks/>
        public validationModeEnum validationMode;

        /// <remarks/>
        [XmlIgnore]
        public bool validationModeSpecified;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerPaymentProfileResponse : ANetApiResponse
    {

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public string validationDirectResponse;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerShippingAddressRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public customerAddressType address;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerShippingAddressResponse : ANetApiResponse
    {

        /// <remarks/>
        public string customerAddressId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerProfileResponse : ANetApiResponse
    {

        /// <remarks/>
        public customerProfileMaskedType profile;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerPaymentProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerPaymentProfileResponse : ANetApiResponse
    {

        /// <remarks/>
        public customerPaymentProfileMaskedType paymentProfile;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerShippingAddressRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerAddressId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerShippingAddressResponse : ANetApiResponse
    {

        /// <remarks/>
        public customerAddressExType address;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateCustomerProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public customerProfileExType profile;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateCustomerProfileResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateCustomerPaymentProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public customerPaymentProfileExType paymentProfile;

        /// <remarks/>
        public validationModeEnum validationMode;

        /// <remarks/>
        [XmlIgnore]
        public bool validationModeSpecified;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateCustomerPaymentProfileResponse : ANetApiResponse
    {

        /// <remarks/>
        public string validationDirectResponse;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateCustomerShippingAddressRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public customerAddressExType address;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateCustomerShippingAddressResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class deleteCustomerProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class deleteCustomerProfileResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class deleteCustomerPaymentProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class deleteCustomerPaymentProfileResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class deleteCustomerShippingAddressRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerAddressId;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class deleteCustomerShippingAddressResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerProfileTransactionRequest : ANetApiRequest
    {

        /// <remarks/>
        public profileTransactionType transaction;

        /// <remarks/>
        public string extraOptions;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class createCustomerProfileTransactionResponse : ANetApiResponse
    {

        /// <remarks/>
        public string directResponse;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class validateCustomerPaymentProfileRequest : ANetApiRequest
    {

        /// <remarks/>
        public string customerProfileId;

        /// <remarks/>
        public string customerPaymentProfileId;

        /// <remarks/>
        public string customerShippingAddressId;

        /// <remarks/>
        public string cardCode;

        /// <remarks/>
        public validationModeEnum validationMode;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class validateCustomerPaymentProfileResponse : ANetApiResponse
    {

        /// <remarks/>
        public string directResponse;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerProfileIdsRequest : ANetApiRequest
    {
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class getCustomerProfileIdsResponse : ANetApiResponse
    {

        /// <remarks/>
        [XmlArrayItem("numericString", IsNullable = false)]
        public string[] ids;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateSplitTenderGroupRequest : ANetApiRequest
    {

        /// <remarks/>
        public string splitTenderId;

        /// <remarks/>
        public splitTenderStatusEnum splitTenderStatus;
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [XmlType(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum splitTenderStatusEnum
    {

        /// <remarks/>
        completed,

        /// <remarks/>
        held,

        /// <remarks/>
        voided,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.42")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [XmlRoot(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public class updateSplitTenderGroupResponse : ANetApiResponse
    {
    }
}
